USE UpperComputer;
GO

INSERT INTO tNoite.EMAIL (codemail,tipoemail,endemail)
VALUES

(18745,'privado','jose.rubens@sql.com'),
(39121,'corporativo','ricardo.brito@dba.com'),
(55322,'academico','roberto.carlos@umf.br'),
(21014,'privado','maria.alice@sql.com'),
(83897,'corporativo','carla.janaina@dba.com'),
(37021,'academico','karina.jesuina@umf.br'),
(40438,'privado','joao.cruz@sql.com'),
(27532,'corporativo','francineide.conceição@dba.com'),
(99732,'academico','carlucio.mariano@umf.br'),
(99875,'academico','sylvanete.clarynda@umf.br');

select * from tNoite.EMAIL;

