USE UpperComputer;
GO

INSERT INTO tNoite.RECURSO (numeroregistro,nomefuncionario,codcargo,codsalario,endereco,codtelefone,codemail)
VALUES

(202,'José Rubens Nicanor de Morae',159,2701,'Rua A, numero 55',1306,18745),
(591,'Ricardo Brito Francisco de Almeida',273,1903,'Rua B, numero 59',1136,39121),
(188,'Roberto Carlos Miranda Lacerda',329,1486,'Rua C, numero 18',9239,55322),
(779,'Maria Alice Ribeiro Fraga',370,2551,'Rua A, numero 77',9057,21014),
(823,'Carla Janaina Aguirre Freitas',424,1640,'Rua J, numero 82',4484,83897),
(562,'Karina Jesuina Fagundes Teles',609,2342,'Rua J, numero 56',7410,37021),
(287,'João da Cruz do Espirito Sant',152,1735,'Rua C, numero 28',2318,40438),
(242,'Francineide Conceição Carbonari Igre',968,2649,'Rua C, numero 24',4231,27532),
(563,'Carlucio Mariano Fagundes Varella',973,2037,'Rua M, numero 56',3664,99732),
(316,'Sylvanete Clarynda Akilles Thor',335,1898,'Rua C, numero 31',7036,99875);

select * from tNoite.RECURSO;